name = "RayTracing"
uuid = "4b51895e-7621-4f2b-bab6-efc159b47762"
authors = ["Abrudsky Martín Ezequiel <mabrudsky07@email.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
